[package]
name = "rust-raytracing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.5"
rand = "0.8"
rayon = "1.10"
almost = "0.2.0"
dyn-clone = "1.0.3"
image = "0.25.1"
